name = "discord-reminder"
main = "src/worker.ts"
compatibility_date = "2025-09-18"

[triggers]
# JST23:14 は UTC14:14。平日と毎月1日を併記
crons = [
  "55 11 * * 2-6",
  "55 11 1 * *"
]

[vars]
# 1) リマインド定義（cronごとに文面とメンションを設定）
#   users/roles は Discord の ID。everyone は "1" で許可。
REMIND_CONFIG = """
[
  {
    "cron": "55 11 * * 2-6",
    "message": "⏰ 20:50です。今日の出勤フォームの入力をお願いします。",
    "users": [],
    "roles": ["1418211829414363207"],
    "everyone": "0"
  },
  {
    "cron": "55 11 1 * *",
    "message": "1ヶ月分の勤怠フォームの確認をお願いします｡",
    "users": [],
    "roles": ["1418211829414363207"],
    "everyone": "0"
  }
]
"""

# 2) グローバル既定（個別定義が空のときに使用）
MENTION_USERS = ""            # "id1,id2"
MENTION_ROLES = ""            # "role1,role2"
ENABLE_EVERYONE = "0"         # "1" で @everyone 許可
TRIGGER_TOKEN = "dev"         # 手動送信用の簡易トークン